-- MySQL Script generated by MySQL Workbench
-- Thu Oct 20 22:00:12 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db-example
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema Cinema_Village
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Cinema_Village` ;

-- -----------------------------------------------------
-- Schema Cinema_Village
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Cinema_Village` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `Cinema_Village` ;

-- -----------------------------------------------------
-- Table `Cinema_Village`.`cinema`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cinema_Village`.`cinema` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cinema_Village`.`cinema` (
  `id_cinema` INT NOT NULL AUTO_INCREMENT,
  `cinemas_name` VARCHAR(60) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `free_parking` ENUM("YES", "NO") NULL DEFAULT NULL COMMENT 'we don´t care about customer´s needs',
  `wheelchair_access` ENUM("YES", "NO") NULL DEFAULT NULL COMMENT 'we don´t care here either',
  PRIMARY KEY (`id_cinema`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Cinema_Village`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cinema_Village`.`address` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cinema_Village`.`address` (
  `id_address` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(40) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `house_number` VARCHAR(15) NOT NULL,
  `zip_code` VARCHAR(6) NULL DEFAULT NULL COMMENT 'with spacebar',
  PRIMARY KEY (`id_address`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Cinema_Village`.`opening_hours`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cinema_Village`.`opening_hours` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cinema_Village`.`opening_hours` (
  `id_opening_hours` INT NOT NULL AUTO_INCREMENT,
  `opening` TIME NOT NULL COMMENT 'example: 12:00',
  `closing` TIME NOT NULL,
  PRIMARY KEY (`id_opening_hours`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Cinema_Village`.`opens_closes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cinema_Village`.`opens_closes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cinema_Village`.`opens_closes` (
  `id_cinema` INT NOT NULL,
  `id_opening_hours` INT NOT NULL,
  INDEX `id_cinema_idx` (`id_cinema` ASC) VISIBLE,
  INDEX `id_opening_hours_idx` (`id_opening_hours` ASC) VISIBLE,
  PRIMARY KEY (`id_cinema`, `id_opening_hours`),
  CONSTRAINT `fk_id_cinema`
    FOREIGN KEY (`id_cinema`)
    REFERENCES `Cinema_Village`.`cinema` (`id_cinema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_opening_hours`
    FOREIGN KEY (`id_opening_hours`)
    REFERENCES `Cinema_Village`.`opening_hours` (`id_opening_hours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Cinema_Village`.`has_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cinema_Village`.`has_address` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cinema_Village`.`has_address` (
  `id_cinema` INT NOT NULL,
  `id_address` INT NOT NULL,
  INDEX `id_cinema_idx` (`id_cinema` ASC) VISIBLE,
  INDEX `id_address_idx` (`id_address` ASC) VISIBLE,
  PRIMARY KEY (`id_cinema`, `id_address`),
  CONSTRAINT `fk1_id_cinema`
    FOREIGN KEY (`id_cinema`)
    REFERENCES `Cinema_Village`.`cinema` (`id_cinema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_address`
    FOREIGN KEY (`id_address`)
    REFERENCES `Cinema_Village`.`address` (`id_address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Cinema_Village`.`films`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cinema_Village`.`films` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cinema_Village`.`films` (
  `id_film` INT NOT NULL AUTO_INCREMENT,
  `films_name` VARCHAR(80) NOT NULL,
  `age_limit` ENUM("3", "7", "12", "16", "18") NOT NULL,
  `footage_minutes` SMALLINT(4) NOT NULL,
  `premiere` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_film`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Cinema_Village`.`has_film`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cinema_Village`.`has_film` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cinema_Village`.`has_film` (
  `id_cinema` INT NOT NULL,
  `id_film` INT NOT NULL,
  INDEX `id_cinema_idx` (`id_cinema` ASC) VISIBLE,
  INDEX `id_film_idx` (`id_film` ASC) VISIBLE,
  PRIMARY KEY (`id_cinema`, `id_film`),
  CONSTRAINT `fk3_id_cinema`
    FOREIGN KEY (`id_cinema`)
    REFERENCES `Cinema_Village`.`cinema` (`id_cinema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_film`
    FOREIGN KEY (`id_film`)
    REFERENCES `Cinema_Village`.`films` (`id_film`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Cinema_Village`.`genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cinema_Village`.`genres` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cinema_Village`.`genres` (
  `id_genre` INT NOT NULL AUTO_INCREMENT,
  `genre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_genre`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Cinema_Village`.`has_genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cinema_Village`.`has_genre` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cinema_Village`.`has_genre` (
  `id_film` INT NOT NULL,
  `id_genre` INT NOT NULL,
  INDEX `id_film_idx` (`id_film` ASC) VISIBLE,
  INDEX `id_genre_idx` (`id_genre` ASC) VISIBLE,
  PRIMARY KEY (`id_film`, `id_genre`),
  CONSTRAINT `fk1_id_film`
    FOREIGN KEY (`id_film`)
    REFERENCES `Cinema_Village`.`films` (`id_film`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_genre`
    FOREIGN KEY (`id_genre`)
    REFERENCES `Cinema_Village`.`genres` (`id_genre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Cinema_Village`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cinema_Village`.`employees` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cinema_Village`.`employees` (
  `id_employee` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_employee`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Cinema_Village`.`works`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cinema_Village`.`works` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cinema_Village`.`works` (
  `id_cinema` INT NOT NULL,
  `id_employee` INT NOT NULL,
  INDEX `id_cinema_idx` (`id_cinema` ASC) VISIBLE,
  INDEX `id_employee_idx` (`id_employee` ASC) VISIBLE,
  PRIMARY KEY (`id_cinema`, `id_employee`),
  CONSTRAINT `fk2_id_cinema`
    FOREIGN KEY (`id_cinema`)
    REFERENCES `Cinema_Village`.`cinema` (`id_cinema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_employee`
    FOREIGN KEY (`id_employee`)
    REFERENCES `Cinema_Village`.`employees` (`id_employee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Cinema_Village`.`positions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cinema_Village`.`positions` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cinema_Village`.`positions` (
  `id_position` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `salary` DECIMAL(11,2) NOT NULL,
  PRIMARY KEY (`id_position`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Cinema_Village`.`has_position`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cinema_Village`.`has_position` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cinema_Village`.`has_position` (
  `id_employee` INT NOT NULL,
  `id_postion` INT NOT NULL,
  INDEX `id_possition_idx` (`id_postion` ASC) VISIBLE,
  INDEX `id_employee_idx` (`id_employee` ASC) VISIBLE,
  PRIMARY KEY (`id_employee`, `id_postion`),
  CONSTRAINT `fk1_id_employee`
    FOREIGN KEY (`id_employee`)
    REFERENCES `Cinema_Village`.`employees` (`id_employee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_possition`
    FOREIGN KEY (`id_postion`)
    REFERENCES `Cinema_Village`.`positions` (`id_position`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Cinema_Village`.`employee_has_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cinema_Village`.`employee_has_address` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cinema_Village`.`employee_has_address` (
  `id_enployee` INT NOT NULL,
  `id_address` INT NOT NULL,
  INDEX `id_employee_idx` (`id_enployee` ASC) VISIBLE,
  INDEX `id_address_idx` (`id_address` ASC) VISIBLE,
  PRIMARY KEY (`id_enployee`, `id_address`),
  CONSTRAINT `fk2_id_employee`
    FOREIGN KEY (`id_enployee`)
    REFERENCES `Cinema_Village`.`employees` (`id_employee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk1_id_address`
    FOREIGN KEY (`id_address`)
    REFERENCES `Cinema_Village`.`address` (`id_address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;